//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSanchez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cambio_H
    {
        public System.DateTime fecha_cambio { get; set; }
        public string usuario_cambio { get; set; }
        public string tipo_cambio { get; set; }
        public decimal idCambio { get; set; }
        public decimal idJugadorEntra { get; set; }
        public decimal idJugadorSale { get; set; }
        public decimal minuto { get; set; }
        public decimal idPartido { get; set; }
        public decimal idEquipo { get; set; }
    }
}
