//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSanchez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecialidadPorJugador
    {
        public decimal idJugador { get; set; }
        public decimal idEspecialidad { get; set; }
        public decimal idDominio { get; set; }
    
        public virtual Dominio Dominio { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual Jugador Jugador { get; set; }
    }
}
