//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSanchez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Federacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Federacion()
        {
            this.CompeticionPorFederacions = new HashSet<CompeticionPorFederacion>();
        }
    
        public decimal idFederacion { get; set; }
        public string nombre { get; set; }
        public decimal idPais { get; set; }
        public System.DateTime FechaCreacionFed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompeticionPorFederacion> CompeticionPorFederacions { get; set; }
        public virtual Pai Pai { get; set; }
    }
}
