//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSanchez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gol
    {
        public decimal idGol { get; set; }
        public decimal idJugador { get; set; }
        public decimal minuto { get; set; }
        public decimal idEquipo { get; set; }
        public decimal idPartido { get; set; }
    
        public virtual Partido Partido { get; set; }
    }
}
