//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSanchez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JugadorPorEquipoPorTorneo
    {
        public decimal idEquipo { get; set; }
        public Nullable<decimal> posicion { get; set; }
        public decimal idJugador { get; set; }
        public decimal idTorneo { get; set; }
        public string evaluacion { get; set; }
    
        public virtual EquipoPorTorneo EquipoPorTorneo { get; set; }
        public virtual Jugador Jugador { get; set; }
    }
}
