//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSanchez.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoBasesSanchezEntities : DbContext
    {
        public ProyectoBasesSanchezEntities()
            : base("name=ProyectoBasesSanchezEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arbitro> Arbitroes { get; set; }
        public virtual DbSet<ArbitroPorPartido> ArbitroPorPartidoes { get; set; }
        public virtual DbSet<Cambio> Cambios { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Competicion> Competicions { get; set; }
        public virtual DbSet<CompeticionPorFederacion> CompeticionPorFederacions { get; set; }
        public virtual DbSet<ContratacionFuncionario> ContratacionFuncionarios { get; set; }
        public virtual DbSet<Contrato> Contratoes { get; set; }
        public virtual DbSet<CorreoFuncionario> CorreoFuncionarios { get; set; }
        public virtual DbSet<DireccionFuncionario> DireccionFuncionarios { get; set; }
        public virtual DbSet<Dominio> Dominios { get; set; }
        public virtual DbSet<Entrenador> Entrenadors { get; set; }
        public virtual DbSet<EntrenadorEquipoTorneo> EntrenadorEquipoTorneos { get; set; }
        public virtual DbSet<Equipo> Equipoes { get; set; }
        public virtual DbSet<EquipoPorTorneo> EquipoPorTorneos { get; set; }
        public virtual DbSet<Especialidad> Especialidads { get; set; }
        public virtual DbSet<EspecialidadPorJugador> EspecialidadPorJugadors { get; set; }
        public virtual DbSet<FechasCalendario> FechasCalendarios { get; set; }
        public virtual DbSet<Federacion> Federacions { get; set; }
        public virtual DbSet<Funcionario> Funcionarios { get; set; }
        public virtual DbSet<Gol> Gols { get; set; }
        public virtual DbSet<Jugador> Jugadors { get; set; }
        public virtual DbSet<JugadorPorEquipoPorTorneo> JugadorPorEquipoPorTorneos { get; set; }
        public virtual DbSet<OfertaFuncionario> OfertaFuncionarios { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<Partido> Partidoes { get; set; }
        public virtual DbSet<Posicion> Posicions { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Socio> Socios { get; set; }
        public virtual DbSet<SuplentesEquipoPartido> SuplentesEquipoPartidoes { get; set; }
        public virtual DbSet<TelefonoFuncionario> TelefonoFuncionarios { get; set; }
        public virtual DbSet<TipoArbitro> TipoArbitroes { get; set; }
        public virtual DbSet<TitularEquipoPartido> TitularEquipoPartidoes { get; set; }
        public virtual DbSet<Titulo> Tituloes { get; set; }
        public virtual DbSet<TituloPorEntrenador> TituloPorEntrenadors { get; set; }
        public virtual DbSet<Torneo> Torneos { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
