//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSanchez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Torneo()
        {
            this.EquipoPorTorneos = new HashSet<EquipoPorTorneo>();
            this.FechasCalendarios = new HashSet<FechasCalendario>();
        }
    
        public decimal idTorneo { get; set; }
        public decimal idCompeticion { get; set; }
        public decimal idFederacion { get; set; }
        public decimal anno { get; set; }
        public string nombre { get; set; }
        public string periodo { get; set; }
    
        public virtual CompeticionPorFederacion CompeticionPorFederacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipoPorTorneo> EquipoPorTorneos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FechasCalendario> FechasCalendarios { get; set; }
    }
}
