//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSanchez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneo_H
    {
        public System.DateTime fecha_cambio { get; set; }
        public string usuario_cambio { get; set; }
        public string tipo_cambio { get; set; }
        public decimal idTorneo { get; set; }
        public decimal idCompeticion { get; set; }
        public decimal idFederacion { get; set; }
        public decimal anno { get; set; }
        public string nombre { get; set; }
        public string periodo { get; set; }
    }
}
